const usersData = [
  {
    id: 1,
    name: "Amit Sharma",
    email: "amit.sharma@gym.com",
    age: 28,
    gender: "Male",
    membershipType: "Gold",
    joinDate: "2023-08-15",
    lastLogin: "2024-04-02 18:45",
    workoutPlan: "Strength Training",
    trainer: "Bret D. Bowers",
    status: "Active",
  },
  {
    id: 2,
    name: "Priya Mehta",
    email: "priya.mehta@gym.com",
    age: 25,
    gender: "Female",
    membershipType: "Platinum",
    joinDate: "2023-06-10",
    lastLogin: "2024-04-02 20:10",
    workoutPlan: "Weight Loss",
    trainer: "Emily White",
    status: "Active",
  },
  {
    id: 3,
    name: "Rahul Verma",
    email: "rahul.verma@gym.com",
    age: 30,
    gender: "Male",
    membershipType: "Silver",
    joinDate: "2023-09-05",
    lastLogin: "2024-03-30 14:20",
    workoutPlan: "Cardio & HIIT",
    trainer: "Robert Wilson",
    status: "Inactive",
  },
  {
    id: 4,
    name: "Anjali Singh",
    email: "anjali.singh@gym.com",
    age: 27,
    gender: "Female",
    membershipType: "Gold",
    joinDate: "2023-11-01",
    lastLogin: "2024-04-01 17:30",
    workoutPlan: "Yoga & Flexibility",
    trainer: "Jessica Taylor",
    status: "Active",
  },
  {
    id: 5,
    name: "Vikram Rathore",
    email: "vikram.rathore@gym.com",
    age: 35,
    gender: "Male",
    membershipType: "Basic",
    joinDate: "2024-01-15",
    lastLogin: "2024-03-28 12:00",
    workoutPlan: "Bodybuilding",
    trainer: "David Lee",
    status: "Inactive",
  },
  {
    id: 6,
    name: "Neha Kapoor",
    email: "neha.kapoor@gym.com",
    age: 24,
    gender: "Female",
    membershipType: "Platinum",
    joinDate: "2023-12-05",
    lastLogin: "2024-04-03 09:30",
    workoutPlan: "Zumba & Dance",
    trainer: "Olivia Martinez",
    status: "Active",
  },
  {
    id: 7,
    name: "Rohan Malhotra",
    email: "rohan.malhotra@gym.com",
    age: 29,
    gender: "Male",
    membershipType: "Silver",
    joinDate: "2023-07-20",
    lastLogin: "2024-04-02 15:20",
    workoutPlan: "Functional Fitness",
    trainer: "Robert Wilson",
    status: "Active",
  },
  {
    id: 8,
    name: "Simran Kaur",
    email: "simran.kaur@gym.com",
    age: 26,
    gender: "Female",
    membershipType: "Gold",
    joinDate: "2023-10-12",
    lastLogin: "2024-04-01 19:10",
    workoutPlan: "Pilates & Core",
    trainer: "Jessica Taylor",
    status: "Active",
  },
  {
    id: 9,
    name: "Arjun Nair",
    email: "arjun.nair@gym.com",
    age: 32,
    gender: "Male",
    membershipType: "Basic",
    joinDate: "2024-02-10",
    lastLogin: "2024-04-02 11:00",
    workoutPlan: "Athletic Performance",
    trainer: "Daniel Harris",
    status: "Inactive",
  },
  {
    id: 10,
    name: "Ritika Das",
    email: "ritika.das@gym.com",
    age: 23,
    gender: "Female",
    membershipType: "Platinum",
    joinDate: "2023-05-18",
    lastLogin: "2024-04-03 08:50",
    workoutPlan: "Rehabilitation & Recovery",
    trainer: "Sophia Anderson",
    status: "Active",
  },
];

export default usersData;
