const users = {
  totalUser: 10,
  Data: [
    {
      id: 1,
      name: "Amit Sharma",
      email: "amit.sharma@gym.com",
      membershipType: "Gold",
      workoutPlan: "Strength Training",
      trainer: "Bret D. Bowers",
      status: "Active",
    },
    {
      id: 2,
      name: "Priya Mehta",
      email: "priya.mehta@gym.com",
      membershipType: "Platinum",
      workoutPlan: "Weight Loss",
      trainer: "Emily White",
      status: "Active",
    },
    {
      id: 3,
      name: "Rahul Verma",
      email: "rahul.verma@gym.com",
      membershipType: "Silver",
      workoutPlan: "Cardio & HIIT",
      trainer: "Robert Wilson",
      status: "Inactive",
    },
    {
      id: 4,
      name: "Anjali Singh",
      email: "anjali.singh@gym.com",
      membershipType: "Gold",
      workoutPlan: "Yoga & Flexibility",
      trainer: "Jessica Taylor",
      status: "Active",
    },
    {
      id: 5,
      name: "Vikram Rathore",
      email: "vikram.rathore@gym.com",
      membershipType: "Basic",
      workoutPlan: "Bodybuilding",
      trainer: "David Lee",
      status: "Inactive",
    },
    {
      id: 6,
      name: "Neha Kapoor",
      email: "neha.kapoor@gym.com",
      membershipType: "Platinum",
      workoutPlan: "Zumba & Dance",
      trainer: "Olivia Martinez",
      status: "Active",
    },
    {
      id: 7,
      name: "Rohan Malhotra",
      email: "rohan.malhotra@gym.com",
      membershipType: "Silver",
      workoutPlan: "Functional Fitness",
      trainer: "Robert Wilson",
      status: "Active",
    },
    {
      id: 8,
      name: "Simran Kaur",
      email: "simran.kaur@gym.com",
      membershipType: "Gold",
      workoutPlan: "Pilates & Core",
      trainer: "Jessica Taylor",
      status: "Active",
    },
    {
      id: 9,
      name: "Arjun Nair",
      email: "arjun.nair@gym.com",
      membershipType: "Basic",
      workoutPlan: "Athletic Performance",
      trainer: "Daniel Harris",
      status: "Inactive",
    },
    {
      id: 10,
      name: "Ritika Das",
      email: "ritika.das@gym.com",
      membershipType: "Platinum",
      workoutPlan: "Rehabilitation & Recovery",
      trainer: "Sophia Anderson",
      status: "Active",
    },
  ],
};
export default users;
